version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  surfact-api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres-db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DATABASENAME: postgres
      DATABASE_SSL: false
    depends_on:
      - postgres-db
    command: npm run start:dev
    ports:
      - '3000:3000'
volumes:
  postgres-data:
  node_modules:

